### ISSUE TITLE
Velocity support?

### ISSUE THREAD

**Issue by xcheez1** [TrueMB/DiscordNotify#4]
like the title says

**Comment by TrueMB** [comment]
Somebody on my Discord already asked about Velocity.
Thatswhy it is already slowly in progress.

I cant tell an exact Date, since I am reworking parts of the plugin to make future Versions easier to Support.
This includes Sponge Support.

It might be in a month. But Issues are coming first for me. So this might delay the progress.

If you can, try using Waterfall or some Fork of Bungeecord until then.

EDIT 05.02.2022: Something came up so I wont be able to add this in a month. Now I definatly cant tell an exact Date.

**Comment by TrueMB** [comment]
Finished building a Multiplatform System.
Nearly implemented everything besides the commands so far.

After that is done I need to test everything.
Possible Alpha Release next Week on my Discord.

**Comment by TrueMB** [comment]
Commands got implemented.
Sponge is a bit difficult and might be added to a later point.
Bungeecord tests started and are mostly finished.

TODO:
- Finishing the last Bungeecord tests
- Bukkit Standalone test
- Velocity test

The Alpha Release should be still to the end of the next weekend.
Alpha Versions are not for productive use!

48147385bb3e4286f46ad2a75e89e434188e8b55

**Comment by TrueMB** [comment]
Bungeecord/Bukkit Test are done and are working like they should.
Velocity test started.

I had some Issues with compiling Velocity correctly. This is fixed now and a first alpha Version should be released tomorrow on my discord.

**Comment by TrueMB** [comment]
Velocity Support got added. You can find the Alpha Version on my Discord.

https://github.com/TrueMB/DiscordNotify/tree/dev
https://discord.gg/YnTRa33QjC
